[toolchain]
# Stable
#channel = "1.75.0" # rustc 1.75.0 (82e1608df 2023-12-21)
# Nightly
channel = "nightly-2024-06-10" # rustc 1.79.0-nightly (0bf471f33 2024-04-13)
components = ["cargo", "clippy", "rustc", "rustfmt", "rust-src", "rust-docs"]
profile = "minimal"
targets = ["wasm32-unknown-unknown"]
